IDE JAR and directory scanning speedup
JetBrains/intellij-plugin-verifier pull request #1030
Opened 2023-11-10 14:53 UTC by novotnyr

- IDE scanning is improved by using the `jar:` schema
- support of `java.nio.FileSystem` is leveraged
- caching of filesystems is implemented when resolving bundled plugins in JARs
- a `JarArchive` class is created to handle basic JAR operations, mainly plugin descriptor resolution

2023-11-14 16:14 UTC, YannCebron requested changes

2023-11-14 16:14 UTC, YannCebron commented on intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/PluginJar.kt
> +    //FIXME close? jarFileSystem.closeLogged()
??

2023-11-14 16:14 UTC, YannCebron commented on intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/CachingJarFileSystemProvider.kt
> + * File system provider that mainains open file systems in an internal cache.
maintains

2023-11-20 08:17 UTC, novotnyr commented on intellij-plugin-structure/structure-base/src/main/kotlin/com/jetbrains/plugin/structure/jar/PluginJar.kt
> +    //FIXME close? jarFileSystem.closeLogged()
Removed, this will not be closed.

2023-11-20 08:53 UTC, novotnyr commented on intellij-plugin-structure/tests/src/test/kotlin/com/jetbrains/plugin/structure/base/utils/PluginJarTest.kt
> +class PluginJarTest {
Added parameterized JAR Filesystem implementation.

2023-11-20 10:27 UTC, YannCebron approved these changes

2023-11-22 13:44 UTC, YannCebron approved these changes

2023-11-23 10:16 UTC, YannCebron approved these changes

2023-11-23 10:17 UTC, merged