Custom XInclude attributes and resolution mechanisms
JetBrains/intellij-plugin-verifier pull request #1097
Opened 2024-05-29 15:40 UTC by novotnyr

- Support `includeIf` and `includeUnless` attributes in the XInclude elements. Properties are resolved against System properties.
- Resolve issues with XMLs referencing each other and being set in `META-INF` and resource roots.
This is an issue in Kotlin plugin. Imagine the following ZIP file contents

```
|- META-INF
     | - plugin.xml
     | - kotlin-core.xml
|- kotlin.plugin.k1.xml
```

The `plugin.xml` conditionally includes `kotlin.plugin.k1.xml` (via `href="kotlin.plugin.k1.xml"`).
Additionally, `kotlin.plugin.k1.xml` includes `kotlin-core.xml`, again via `href="kotlin-core.xml"`.

This is not in line with XInclude specification. However, the support for such scenarios is implemented.

- See also [MP-6594](https://youtrack.jetbrains.com/issue/MP-6594) Could not find bundled plugin with ID: 'org.jetbrains.kotlin'

2024-05-31 09:28 UTC, chrkv approved these changes

2024-06-03 12:17 UTC, YannCebron requested changes

2024-06-06 12:43 UTC, novotnyr commented on intellij-plugin-structure/structure-intellij/src/main/java/com/jetbrains/plugin/structure/intellij/xinclude/XIncluder.kt
> +  private fun Properties.isTrue(key: String?): Boolean {
After some discussion with @develar, the ability to `includeIf` and `includeUnless` is conditionally enabled.

By default, it requires a `com.jetbrains.plugin.structure.intellij.xinclude.isResolvingConditionalIncludes` system property to be set to `true`. By default, an `include` element with either of these attributes will be ignored and not processed for inclusion.

This allows to use the `structure` library with conditional XInclude support, but being disabled by default as it is used only in the Kotlin plugin.

2024-06-06 12:46 UTC, YannCebron commented
Please add a comment in relevant places that this is a special case for Kotlin plugin and not a regular feature for plugin.xml.

2024-06-06 12:46 UTC, YannCebron approved these changes

2024-06-06 15:08 UTC, merged