CLI switch to suppress internal API usages by internal plugins
JetBrains/intellij-plugin-verifier pull request #999
Opened 2023-09-12 14:33 UTC by novotnyr

Add a `--suppress-internal-api-usages` switch to disable internal API usages reporting by internal plugins.

See #952 for original implementation, which did not provide CLI switch.

2023-09-12 15:51 UTC, LChernigovskaya approved these changes

2023-09-13 09:37 UTC, YannCebron requested changes

2023-09-13 09:37 UTC, YannCebron commented on README.md
> +This option is used by JetBrains MarketPlace by default.
JetBrains Market<p>lace

"internal plugins" is misleading, it should be "plugins from JetBrains" (see also below)

the cmd-line option should also be renamed

2023-09-13 09:37 UTC, YannCebron commented on intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParams.kt
> +   * Internal plugins that use internal APIs will not be reported.
see above

2023-09-13 10:25 UTC, YannCebron requested changes

2023-09-13 10:25 UTC, YannCebron commented on README.md
> +This option is used by JetBrains MarketPlace by default.
`JetBrains Market<p>lace`

2023-09-13 10:25 UTC, YannCebron commented on intellij-plugin-verifier/verifier-cli/src/main/java/com/jetbrains/pluginverifier/tasks/checkPlugin/CheckPluginParams.kt
> +   * Internal plugins that use internal APIs will not be reported.
still "internal plugins" in doc

2023-09-13 11:12 UTC, YannCebron approved these changes

2023-09-13 11:29 UTC, merged